name: adoptandlove
description: Adopt & Love mobile application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 3.0.2+30002

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^3.0.1
  async: ^2.4.1
  dio: ^4.0.4
  sqflite: ^1.0.0
  streamqflite: ^1.0.0
  equatable: ^0.2.3
  cached_network_image: 2.5.1	
  url_launcher: ^6.0.20
  shared_preferences: ^0.5.7+2
  font_awesome_flutter: ^8.8.1
  smooth_page_indicator: ^0.2.0
  intl: ^0.17.0
  firebase_core: ^1.10.2
  firebase_analytics: 9.0.5	
  firebase_crashlytics: 2.5.1
  firebase_performance: 0.8.0+5 

  device_info: ^0.4.2+4
  pinch_zoom: ^1.0.0

  firebase_auth: ^3.3.9
  flutterfire_ui: 0.3.5+1
  firebase_messaging: ^11.2.15
dependency_overrides:
  # For firebase_ui
  flutter_svg: 1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.0.1
  flutter_launcher_icons: 0.9.2 	


flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ic_home.png
    - assets/no_pets.png
    - assets/cat.png
    - assets/dog.png
    - assets/two_logos.png
    - assets/anonymous_avatar.png
    - assets/get_pet_logo.png
    - assets/onboarding/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
